#!/usr/bin/env python3
"""
Generate Goshenite distrobox "lab" images from the Kali reverse-engineering data.

Each lab is a FROM kalilinux/kali-rolling image that installs the corresponding
kali-tools-* metapackage (plus a tiny Goshenite wrapper: shell aliases, distrobox
export hints, /usr/share/goshenite marker). This gives Glass users access to the
~72% of Kali tooling that has no Fedora RPM, while the immutable Aurora/Bluefin host
stays thin.

Output per lab: labs/<lab>/Dockerfile  (+ an auto-generated NOTE).
"""
from __future__ import annotations
import argparse, json, shutil
from pathlib import Path

HERE = Path(__file__).resolve().parent
# Vendored split data (copied from glass-bundles/references/kali/glass-split.json) so
# this repo is self-contained in CI. Falls back to a local glass-bundles checkout.
SPLIT = HERE / "references" / "glass-split.json"
if not SPLIT.exists():
    SPLIT = Path("/home/kali/goshenite/glass-bundles/references/kali/glass-split.json")

# bundle key -> lab image name (must match glass-bundles materializer LAB_ALIAS)
ALIAS = {"information-gathering": "osint", "reverse-engineering": "reversing",
         "windows-resources": "windows"}
# bundles that get a dedicated lab
NEEDS_LAB = {"web","exploitation","vulnerability","forensics","reverse-engineering",
"information-gathering","passwords","wireless","voip","windows-resources",
"post-exploitation","database","sniffing-spoofing","fuzzing",
"social-engineering","identify","protect","detect","respond","recover"}


def render(lab: str, kali_tools: str) -> str:
    return f"""\
# syntax=docker/dockerfile:1
# Goshenite lab: {lab}
# Base: Kali rolling. Installs kali-tools-{kali_tools} so the {lab} bundle's
# unpackaged (non-Fedora) tools are reachable via `distrobox enter {lab}`.
# Auto-generated by generate-labs.py — do not edit by hand.
FROM kalilinux/kali-rolling:latest

ENV DEBIAN_FRONTEND=noninteractive \\
    GOSHENITE_LAB={lab}

RUN apt-get update && apt-get install -y --no-install-recommends \\
        kali-tools-{kali_tools} ca-certificates \\
    && rm -rf /var/lib/apt/lists/*

# distrobox may already be present in the Kali base; install if available, ignore otherwise.
RUN apt-get update && (apt-get install -y --no-install-recommends distrobox || true) \\
    && rm -rf /var/lib/apt/lists/*

# Goshenite marker + convenience alias file for distrobox-exported shells.
RUN mkdir -p /usr/share/goshenite \\
    && echo '{{"lab":"{lab}","kali_tools":"kali-tools-{kali_tools}"}}' > /usr/share/goshenite/lab-info.json \\
    && printf '# Goshenite {lab} lab\\nalias goshenite-lab="echo {lab} (kali-tools-{kali_tools})"\\n' > /etc/profile.d/goshenite-{lab}-alias.sh

CMD ["/bin/bash"]
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=HERE / "labs")
    ap.add_argument("--only", nargs="*")
    args = ap.parse_args()
    split = json.loads(SPLIT.read_text())
    args.out.mkdir(parents=True, exist_ok=True)
    written = []
    for name, data in sorted(split.items()):
        if name not in NEEDS_LAB:
            continue
        lab = ALIAS.get(name, name)
        if args.only and lab not in args.only:
            continue
        d = args.out / lab
        d.mkdir(parents=True, exist_ok=True)
        (d / "Dockerfile").write_text(render(lab, name))
        written.append(lab)
    print(f"wrote {len(written)} lab Dockerfiles: {', '.join(written)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
